-- Seed packaging materials extracted from the official Aspee list.
-- Count-based materials are stocked in Pieces.
-- Weight-based packaging foils/PVC are purchased in Kilograms and stocked/issued in Grams.

DO $$
BEGIN

IF EXISTS (SELECT 1 FROM products WHERE sku = 'PM-PC-001') THEN
  RAISE NOTICE 'Packaging materials already seeded; skipping.';
  RETURN;
END IF;

INSERT INTO products (
  name, sku, unit, material_type, is_controlled_drug, reorder_level,
  purchase_unit, issue_unit, bulk_unit, bulk_to_base_ratio
) VALUES
  ('Aspimol Plus Inners',           'PM-PC-001', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Plus Outers',           'PM-PC-002', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol X Inners',              'PM-PC-003', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol X Outers',              'PM-PC-004', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Extra Capsules Inners',         'PM-PC-005', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Extra Capsules Outers',         'PM-PC-006', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimak Capsules Inners',       'PM-PC-007', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Forte Capsules Inners', 'PM-PC-008', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Forte Capsules Outers', 'PM-PC-009', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('B.Co Outers',                   'PM-PC-010', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Folic Acid Outers',             'PM-PC-011', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Multivite Outers',              'PM-PC-012', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Diazepam 5 Outers',             'PM-PC-013', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Diazepam 10 Outers',            'PM-PC-014', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Ascold Outers',                 'PM-PC-015', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspitone Syrup Outers',         'PM-PC-016', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspitone Syrup Labels',         'PM-PC-017', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspidyne Outers',               'PM-PC-018', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspidyne Labels',               'PM-PC-019', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Lista Outers',                  'PM-PC-020', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Lista Labels',                  'PM-PC-021', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Haematose Outers',              'PM-PC-022', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Haematose Labels',              'PM-PC-023', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspicof Outers',                'PM-PC-024', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspicof Labels',                'PM-PC-025', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Kindervite Outers',             'PM-PC-026', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Kindervite Labels',             'PM-PC-027', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Outers',                'PM-PC-028', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Labels',                'PM-PC-029', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Codacof Outers',                'PM-PC-030', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Codacof Labels',                'PM-PC-031', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Kindercof Syrup Outers',        'PM-PC-032', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Kindercof Syrup Labels',        'PM-PC-033', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Adultcof Syrup Outers',         'PM-PC-034', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Adultcof Syrup Labels',         'PM-PC-035', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Quinine Syrup Outers',          'PM-PC-036', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Quinine Syrup Labels',          'PM-PC-037', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Asprolex F Syrup Outers',       'PM-PC-038', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Asprolex F Syrup Labels',       'PM-PC-039', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 0.5% Inners',        'PM-PC-040', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 0.5% Outers',        'PM-PC-041', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 0.5% Labels',        'PM-PC-042', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 1% Inners',          'PM-PC-043', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 1% Outers',          'PM-PC-044', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 1% Labels',          'PM-PC-045', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('125ml Plastic Bottles',         'PM-PC-046', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('125ml PP Cups',                 'PM-PC-047', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('200ml Plastic Bottles',         'PM-PC-048', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Measuring Cups',                'PM-PC-049', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('PVC 152',                       'PM-KG-001', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('PVC 174',                       'PM-KG-002', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('PVC 184',                       'PM-KG-003', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('PVC 78',                        'PM-KG-004', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Folic Acid Foil',               'PM-KG-005', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Astradol Foil',                 'PM-KG-006', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('B.Co Tablet Foil',              'PM-KG-007', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspimol Plus Foil',             'PM-KG-008', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspimol X Foil',                'PM-KG-009', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspidyne Capsules Foil',        'PM-KG-010', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Haematose Foil',                'PM-KG-011', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Diazepam 10 Tablet Foil',       'PM-KG-012', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Diazepam 5 Tablet Foil',        'PM-KG-013', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Ascold Foil',                   'PM-KG-014', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspimol Forte Foil',            'PM-KG-015', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Multivite Foil',                'PM-KG-016', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Extra Capsules Foil',           'PM-KG-017', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspimak Forte Foil',            'PM-KG-018', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Aspimak Caps Foil',             'PM-KG-019', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('Ascold Tablet Foil',            'PM-KG-020', 'Grams',  'Packaging Material', false, 0, 'Kilograms', 'Grams', null, null),
  ('125 Syrup Carton',              'PM-CT-001', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Lista Syrup Carton',            'PM-CT-002', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspidyne Syrup Carton',         'PM-CT-003', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspitone Syrup Carton',         'PM-CT-004', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Haematose Syrup Carton',        'PM-CT-005', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspidyne Syrup (NJ) Carton',    'PM-CT-006', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 1% Carton',          'PM-CT-007', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Nasal Drop 0.5% Carton',        'PM-CT-008', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('SDA Carton',                    'PM-CT-009', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('125ml Syrup (NJ) Carton',       'PM-CT-010', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Multivite Tablet Carton',       'PM-CT-011', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Folic Acid Tablet Carton',      'PM-CT-012', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('B.Co Tablet Carton',            'PM-CT-013', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimak Tablet Carton',         'PM-CT-014', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol Plus Tablet Carton',    'PM-CT-015', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Aspimol X Tablet Carton',       'PM-CT-016', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Diazepam 10 Tablet Carton',     'PM-CT-017', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Diazepam 5 Tablet Carton',      'PM-CT-018', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Extra Tablet Carton',           'PM-CT-019', 'Pieces', 'Packaging Material', false, 0, null, null, null, null),
  ('Astradol-P Tablet Carton',      'PM-CT-020', 'Pieces', 'Packaging Material', false, 0, null, null, null, null);

RAISE NOTICE 'Done: packaging materials seeded successfully.';

END $$;
